//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.10 at 09:27:09 AM WIB 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://test.inquiry/")
package com.testing.miniproject.model;
